# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anonymongo < Formula
  desc "A CLI tool to redact sensitive values from MongoDB log files"
  homepage "https://github.com/yuvalherziger/anonymongo"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.0.3/anonymongo_Darwin_x86_64.tar.gz"
      sha256 "7667adc2bcda1fb07e5949fb82d67b6ceeb1507f2b2aae14d0476a4ef3bdd951"

      def install
        bin.install "anonymongo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.0.3/anonymongo_Darwin_arm64.tar.gz"
      sha256 "6ec5f80f022739721009e2547c91f14c97a2b5d73a5f2cb41985a20d3d458f5c"

      def install
        bin.install "anonymongo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.0.3/anonymongo_Linux_x86_64.tar.gz"
      sha256 "21e34498436df733896bf86698748fbde02b20f5d41ac6939c73a3b6fdf46a99"
      def install
        bin.install "anonymongo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.0.3/anonymongo_Linux_arm64.tar.gz"
      sha256 "32126b6ef59d950ee2ba0bcfbd7b26c8202c872d6ab329fb2ad2a8038f19113c"
      def install
        bin.install "anonymongo"
      end
    end
  end

  def caveats
    <<~EOS
      To test the installation, run: anonymongo version
    EOS
  end
end
