# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anonymongo < Formula
  desc "A CLI tool to redact sensitive values from MongoDB log files"
  homepage "https://github.com/yuvalherziger/anonymongo"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.0/anonymongo_Darwin_x86_64.tar.gz"
      sha256 "bca9129c4d26e0642a2e6cb22c4f7502ada7b5b0cbe339b244291af38b03d67a"

      def install
        bin.install "anonymongo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.0/anonymongo_Darwin_arm64.tar.gz"
      sha256 "397ab1134906de3e30790392078a5554e94ca3262de9bd459a51b1fe5afc1345"

      def install
        bin.install "anonymongo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.0/anonymongo_Linux_x86_64.tar.gz"
      sha256 "e6172ed68c977ed29d688b14cdef2ad590be4450a068de2550962279c7ea9a81"
      def install
        bin.install "anonymongo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.0/anonymongo_Linux_arm64.tar.gz"
      sha256 "70ba50f8ba166a45bf7c4fa81880bbcbc0ec037c6afbfb0860849a4e4634e0cf"
      def install
        bin.install "anonymongo"
      end
    end
  end

  def caveats
    <<~EOS
      To test the installation, run: anonymongo version
    EOS
  end
end
