# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anonymongo < Formula
  desc "A CLI tool to redact sensitive values from MongoDB log files"
  homepage "https://github.com/yuvalherziger/anonymongo"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.1/anonymongo_Darwin_x86_64.tar.gz"
      sha256 "f6ed593b9a02237656ccb422e55950896bb51e6975584e8f879b65c93523743d"

      def install
        bin.install "anonymongo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.1/anonymongo_Darwin_arm64.tar.gz"
      sha256 "bb603210553061a0d696ef221bd96094eea8b5c1a4237e17ac7628eaefffdb36"

      def install
        bin.install "anonymongo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.1/anonymongo_Linux_x86_64.tar.gz"
      sha256 "9733dcfa0393eb762948e0d35e9359b0f5bbd87ab5dc3da023451fc6bd03497d"
      def install
        bin.install "anonymongo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yuvalherziger/anonymongo/releases/download/1.3.1/anonymongo_Linux_arm64.tar.gz"
      sha256 "6d459bbac5c2ed972c35cf8420f7eba4e9f85d6bbaee15fb14da2a95ca59f941"
      def install
        bin.install "anonymongo"
      end
    end
  end

  def caveats
    <<~EOS
      To test the installation, run: anonymongo version
    EOS
  end
end
