# This file was generated by GoReleaser. DO NOT EDIT.
cask "anonymongo" do
  desc "A CLI tool to redact sensitive values from MongoDB log files"
  homepage "https://github.com/yuvalherziger/homebrew"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anonymongo"

  on_macos do
    on_intel do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.3.1/anonymongo_Darwin_x86_64.tar.gz"
      sha256 "c246e385f7fbc0994bc2a9a5e9daf7da67b2cd4eb2c4b078f84c59141ef5473e"
    end
    on_arm do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.3.1/anonymongo_Darwin_arm64.tar.gz"
      sha256 "8eab10b33e3003c76bbb64a4e8e1a15f36bd23da637493b915e36a360f368b27"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.3.1/anonymongo_Linux_x86_64.tar.gz"
      sha256 "09ab7676313901527cb85af7d22713188cc896bfc07c817de235a416fa9c5c6d"
    end
    on_arm do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.3.1/anonymongo_Linux_arm64.tar.gz"
      sha256 "a2868d3c7e64f3695115bbf373692becb92d569895e979813f69c3d163918526"
    end
  end

  caveats do
    "To test the installation, run: anonymongo version"
  end

  # No zap stanza required
end
