# This file was generated by GoReleaser. DO NOT EDIT.
cask "anonymongo" do
  desc "A CLI tool to redact sensitive values from MongoDB log files"
  homepage "https://github.com/yuvalherziger/homebrew"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "anonymongo"

  on_macos do
    on_intel do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.1.0/anonymongo_Darwin_x86_64.tar.gz"
      sha256 "55a884bc66332337ffd87611071ecd84242da24a210bddacfbe3643aabe1681c"
    end
    on_arm do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.1.0/anonymongo_Darwin_arm64.tar.gz"
      sha256 "ad92739543b4d0adae832b87148bbd221e02bd1e1553ff6d432b33bd56891f8b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.1.0/anonymongo_Linux_x86_64.tar.gz"
      sha256 "57ef0b7be02ad443d945ddacaeac52a0afc05b2fe22c6eb5f5d7aa53943a38a6"
    end
    on_arm do
      url "https://github.com/yuvalherziger/anonymongo/releases/download/0.1.0/anonymongo_Linux_arm64.tar.gz"
      sha256 "5dab8a211ba3c47fa3bae00bd0a4761c261aff7921e19f2f2ba9975f1bb548a4"
    end
  end

  caveats do
    "To test the installation, run: anonymongo version"
  end

  # No zap stanza required
end
